services:
  backend:
    build: 
      context: ./backend
    image: task-manager-backend:1.0
    container_name: task-manager-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskmanager
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: task-manager-postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: