services:
  postgres:
    image: postgres:17
    container_name: task-manager-postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: